name: vnc
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.8.4
  - matplotlib-venn=0.11.10
  - networkx=3.1
  - numpy=1.26.4
  - pyarrow=14.0.2
  - python=3.12.2
  - scikit-learn=1.4.2
  - scipy=1.13.0
  - seaborn=0.12.2
  - setuptools=68.2.2
  - tqdm=4.66.4
